// Generated by CoffeeScript 1.6.3
(function() {
  var Utils;

  Utils = (function() {
    var instance;

    instance = null;

    Utils.prototype.log_active = false;

    function Utils() {
      if (Utils.instance != null) {
        return Utils.instance;
      }
      Utils.instance = this;
    }

    Utils.prototype.log = function(msg) {
      if (this.log_active) {
        return console.log(msg);
      }
    };

    return Utils;

  })();

  module.exports = Utils;

}).call(this);
